version: '3'
services:
  gateway:
    ports:
      - "5211:80"
    volumes:
      - "./volumes/gateway/config:/app/Config"
  bc-api:
    ports:
      - "5221:80"
    environment:
      - ConnectionStrings__AuthenticationContext=Server=sql-server,1433;Initial Catalog=BC;User=sa;Password=Password123
      - ConnectionStrings__MastersContext=Server=sql-server,1433;Initial Catalog=BC;User=sa;Password=Password123
      - ConnectionStrings__BookingContext=Server=sql-server,1433;Initial Catalog=BC;User=sa;Password=Password123
      - ConnectionStrings__BalanceContext=Server=sql-server,1433;Initial Catalog=BC;User=sa;Password=Password123
      - ConnectionStrings__FeedbackContext=Server=sql-server,1433;Initial Catalog=BC;User=sa;Password=Password123
      - Services__MastersList__FilesServiceInternalUrl=http://gateway/api/files/
      - Services__MastersList__FilesServicePublicUrl="http://localhost:5211/api/files/"
      - RabbitMQEventBus__Host=rabbitmq
      - RabbitMQEventBus__Port=5672
      - ASPNETCORE_URLS=http://+:80
  sql-server:
    ports:
      - "5231:1433"
    volumes:
      - "./volumes/sql-server/data:/var/opt/mssql/data"
  rabbitmq:
    ports:
      - "5241:5672"
      - "5251:15672"
  bc-client:
    build:
      dockerfile: "BC.Common/Dockerfile.Client.Local-02"
    ports:
      - "5261:80"
  bc-master:
    build:
      dockerfile: "BC.Common/Dockerfile.Master.Local-02"
    ports:
      - "5271:80"
  #  master:
  #    build:
  #      context: .
  #      dockerfile: "BC.Master/Dockerfile"
  #    ports:
  #    - "5003:80"
  #  saloon:
  #    build:
  #      context: .
  #      dockerfile: "BC.Saloon/Dockerfile"
  #    ports:
  #    - "5004:80"


