version: '3'
services:
  gateway:
    build:
      context: .
      dockerfile: "BC.APIGateway/Dockerfile"
    volumes:
      - "./volumes/gateway/config:/app/Config"
    environment:
      - ASPNETCORE_URLS=http://+:80
  bc-api:
    build:
      context: .
      dockerfile: "BC.API/Dockerfile"
    environment:
      - ConnectionStrings__AuthenticationContext=Server=sql-server,1433;Initial Catalog=BC;User=sa;Password=Password123
      - ConnectionStrings__MasterContext=Server=sql-server,1433;Initial Catalog=BC;User=sa;Password=Password123
      - ASPNETCORE_URLS=http://+:80
    volumes:
      - "./volumes/bc-api/Data:/app/Data"
    depends_on:
      - sql-server
      - rabbitmq
  sql-server:
    image: "mcr.microsoft.com/mssql/server"
    environment:
      SA_PASSWORD: "Password123"
      ACCEPT_EULA: "Y"
    volumes:
      - "./volumes/sql-server/data:/var/opt/mssql/data"
  rabbitmq:
    image: "rabbitmq:3-management"
  bc-client:
    build:
      context: .
  bc-master:
    build:
      context: .
  #  master:
  #    build:
  #      context: .
  #      dockerfile: "BC.Master/Dockerfile"
  #    ports:
  #    - "5003:80"
  #  saloon:
  #    build:
  #      context: .
  #      dockerfile: "BC.Saloon/Dockerfile"
  #    ports:
  #    - "5004:80"


