version: '3'
services:
  gateway:
    ports:
      - "5210:80"
    volumes:
      - "./volumes/gateway/config:/app/Config"
  bc-api:
    ports:
      - "5220:80"
    environment:
      - ConnectionStrings__AuthenticationContext=Server=sql-server,1433;Initial Catalog=BC;User=sa;Password=Password123
      - ConnectionStrings__MasterContext=Server=sql-server,1433;Initial Catalog=BC;User=sa;Password=Password123
      - ASPNETCORE_URLS=http://+:80
  sql-server:
    ports:
      - "5230:1433"
    volumes:
      - "./volumes/sql-server/data:/var/opt/mssql/data"
  rabbitmq:
    ports:
      - "5240:5672"
      - "5250:15672"
  bc-client:
    build:
      dockerfile: "BC.Client/Dockerfile.Local-01"
    ports:
      - "5260:80"
  #  master:
  #    build:
  #      context: .
  #      dockerfile: "BC.Master/Dockerfile"
  #    ports:
  #    - "5003:80"
  #  saloon:
  #    build:
  #      context: .
  #      dockerfile: "BC.Saloon/Dockerfile"
  #    ports:
  #    - "5004:80"


