version: '3'
services:
  gateway:
    restart: always
    build:
      context: .
      dockerfile: "BC.APIGateway/Dockerfile"
    volumes:
      - "./volumes/gateway/config:/app/Config"
    environment:
      - ASPNETCORE_URLS=http://+:80
  bc-api:
    restart: always
    build:
      context: .
      dockerfile: "BC.API/Dockerfile"
    environment:
      - ASPNETCORE_URLS=http://+:80
    volumes:
      - "./volumes/bc-api/Data:/app/Data"
    depends_on:
      - sql-server
      - rabbitmq
  sql-server:
    restart: always
    image: "mcr.microsoft.com/mssql/server"
    environment:
      SA_PASSWORD: "Password123"
      ACCEPT_EULA: "Y"
    volumes:
      - "./volumes/sql-server/data:/var/opt/mssql/data"
  rabbitmq:
    restart: always
    image: "rabbitmq:3-management"
  bc-client:
    build:
      context: .
  bc-master:
    build:
      context: .