POST http://localhost:5211/api/booking/add-working-week
Content-Type: application/json
Connection: keep-alive

{
"MasterId": "DEFF0772-EACB-4935-8623-7700C58B930A",
"MondayDate": "2020-10-19T00:00:00",
"DaysToWork": [1,2,3],
"StartTime": "8:30",
"EndTime": "18:30"
}
