POST http://localhost:5210/api/balance/increase-balance
Content-Type: application/json
Connection: keep-alive
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6IjFkYjY4YTZlLTQ5M2UtNDYxYS1hZmYxLTA4ZDg4NGNiNzI3MSIsIlVzZXJOYW1lIjoiMjc5NTkwNTctMTg1Ny00Yjc4LWJkZmUtNjM4ODgzYmVkNGYxIiwibmJmIjoxNjA1MjY2NDk1LCJleHAiOjE2MDUyNzI0OTUsImlzcyI6ImRlZmF1bHRTZXJ2ZXIiLCJhdWQiOiJkZWZhdWx0Q2xpZW50In0.XPkW2DzfAP2HQ5srLJ4UoY5YSmgN01KyFtqxQZZE3aU

###
