/* tslint:disable */
/* eslint-disable */
//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v13.10.7.0 (NJsonSchema v10.3.9.0 (Newtonsoft.Json v11.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------
// ReSharper disable InconsistentNaming

import { mergeMap as _observableMergeMap, catchError as _observableCatch } from 'rxjs/operators';
import { Observable, throwError as _observableThrow, of as _observableOf } from 'rxjs';
import { Injectable, Inject, Optional, InjectionToken } from '@angular/core';
import { HttpClient, HttpHeaders, HttpResponse, HttpResponseBase } from '@angular/common/http';

export const API_BASE_URL = new InjectionToken<string>('API_BASE_URL');

@Injectable()
export class BalanceClient {
    private http: HttpClient;
    private baseUrl: string;
    protected jsonParseReviver: ((key: string, value: any) => any) | undefined = undefined;

    constructor(@Inject(HttpClient) http: HttpClient, @Optional() @Inject(API_BASE_URL) baseUrl?: string) {
        this.http = http;
        this.baseUrl = baseUrl !== undefined && baseUrl !== null ? baseUrl : "";
    }

    /**
     * @param userId (optional) 
     * @return Success
     */
    increaseBalance(userId: string | undefined): Observable<void> {
        let url_ = this.baseUrl + "/balance/increase-balance";
        url_ = url_.replace(/[?&]$/, "");

        let options_ : any = {
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
                "UserId": userId !== undefined && userId !== null ? "" + userId : "",
            })
        };

        return this.http.request("post", url_, options_).pipe(_observableMergeMap((response_ : any) => {
            return this.processIncreaseBalance(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processIncreaseBalance(<any>response_);
                } catch (e) {
                    return <Observable<void>><any>_observableThrow(e);
                }
            } else
                return <Observable<void>><any>_observableThrow(response_);
        }));
    }

    protected processIncreaseBalance(response: HttpResponseBase): Observable<void> {
        const status = response.status;
        const responseBlob =
            response instanceof HttpResponse ? response.body :
            (<any>response).error instanceof Blob ? (<any>response).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }}
        if (status === 200) {
            return blobToText(responseBlob).pipe(_observableMergeMap(_responseText => {
            return _observableOf<void>(<any>null);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap(_responseText => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf<void>(<any>null);
    }
}

@Injectable()
export class MasterListClient {
    private http: HttpClient;
    private baseUrl: string;
    protected jsonParseReviver: ((key: string, value: any) => any) | undefined = undefined;

    constructor(@Inject(HttpClient) http: HttpClient, @Optional() @Inject(API_BASE_URL) baseUrl?: string) {
        this.http = http;
        this.baseUrl = baseUrl !== undefined && baseUrl !== null ? baseUrl : "";
    }

    /**
     * @param cityId (optional) 
     * @param serviceTypeIds (optional) 
     * @param startHour (optional) 
     * @param endHour (optional) 
     * @param skip (optional) 
     * @param take (optional) 
     * @return Success
     */
    getMasters(cityId: string | null | undefined, serviceTypeIds: string[] | null | undefined, startHour: number | null | undefined, endHour: number | null | undefined, skip: number | undefined, take: number | undefined): Observable<MasterRes[]> {
        let url_ = this.baseUrl + "/masters-list/get-masters?";
        if (cityId !== undefined && cityId !== null)
            url_ += "CityId=" + encodeURIComponent("" + cityId) + "&";
        if (serviceTypeIds !== undefined && serviceTypeIds !== null)
            serviceTypeIds && serviceTypeIds.forEach(item => { url_ += "ServiceTypeIds=" + encodeURIComponent("" + item) + "&"; });
        if (startHour !== undefined && startHour !== null)
            url_ += "StartHour=" + encodeURIComponent("" + startHour) + "&";
        if (endHour !== undefined && endHour !== null)
            url_ += "EndHour=" + encodeURIComponent("" + endHour) + "&";
        if (skip === null)
            throw new Error("The parameter 'skip' cannot be null.");
        else if (skip !== undefined)
            url_ += "Skip=" + encodeURIComponent("" + skip) + "&";
        if (take === null)
            throw new Error("The parameter 'take' cannot be null.");
        else if (take !== undefined)
            url_ += "Take=" + encodeURIComponent("" + take) + "&";
        url_ = url_.replace(/[?&]$/, "");

        let options_ : any = {
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
                "Accept": "text/plain"
            })
        };

        return this.http.request("get", url_, options_).pipe(_observableMergeMap((response_ : any) => {
            return this.processGetMasters(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processGetMasters(<any>response_);
                } catch (e) {
                    return <Observable<MasterRes[]>><any>_observableThrow(e);
                }
            } else
                return <Observable<MasterRes[]>><any>_observableThrow(response_);
        }));
    }

    protected processGetMasters(response: HttpResponseBase): Observable<MasterRes[]> {
        const status = response.status;
        const responseBlob =
            response instanceof HttpResponse ? response.body :
            (<any>response).error instanceof Blob ? (<any>response).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }}
        if (status === 200) {
            return blobToText(responseBlob).pipe(_observableMergeMap(_responseText => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            if (Array.isArray(resultData200)) {
                result200 = [] as any;
                for (let item of resultData200)
                    result200!.push(MasterRes.fromJS(item));
            }
            return _observableOf(result200);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap(_responseText => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf<MasterRes[]>(<any>null);
    }

    /**
     * @return MasterRes
     */
    getMasterById(id: string): Observable<MasterRes> {
        let url_ = this.baseUrl + "/masters-list/get-master-by-id/{id}";
        if (id === undefined || id === null)
            throw new Error("The parameter 'id' must be defined.");
        url_ = url_.replace("{id}", encodeURIComponent("" + id));
        url_ = url_.replace(/[?&]$/, "");

        let options_ : any = {
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
                "Accept": "text/plain"
            })
        };

        return this.http.request("get", url_, options_).pipe(_observableMergeMap((response_ : any) => {
            return this.processGetMasterById(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processGetMasterById(<any>response_);
                } catch (e) {
                    return <Observable<MasterRes>><any>_observableThrow(e);
                }
            } else
                return <Observable<MasterRes>><any>_observableThrow(response_);
        }));
    }

    protected processGetMasterById(response: HttpResponseBase): Observable<MasterRes> {
        const status = response.status;
        const responseBlob =
            response instanceof HttpResponse ? response.body :
            (<any>response).error instanceof Blob ? (<any>response).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }}
        if (status === 200) {
            return blobToText(responseBlob).pipe(_observableMergeMap(_responseText => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = MasterRes.fromJS(resultData200);
            return _observableOf(result200);
            }));
        } else if (status === 400) {
            return blobToText(responseBlob).pipe(_observableMergeMap(_responseText => {
            let result400: any = null;
            let resultData400 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result400 = BadAPIResponse.fromJS(resultData400);
            return throwException("BadAPIResponse", status, _responseText, _headers, result400);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap(_responseText => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf<MasterRes>(<any>null);
    }

    /**
     * @return PublishMasterResult
     */
    publishMaster(id: string): Observable<PublishMasterResult> {
        let url_ = this.baseUrl + "/masters-list/publish-master/{id}";
        if (id === undefined || id === null)
            throw new Error("The parameter 'id' must be defined.");
        url_ = url_.replace("{id}", encodeURIComponent("" + id));
        url_ = url_.replace(/[?&]$/, "");

        let options_ : any = {
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
                "Accept": "text/plain"
            })
        };

        return this.http.request("post", url_, options_).pipe(_observableMergeMap((response_ : any) => {
            return this.processPublishMaster(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processPublishMaster(<any>response_);
                } catch (e) {
                    return <Observable<PublishMasterResult>><any>_observableThrow(e);
                }
            } else
                return <Observable<PublishMasterResult>><any>_observableThrow(response_);
        }));
    }

    protected processPublishMaster(response: HttpResponseBase): Observable<PublishMasterResult> {
        const status = response.status;
        const responseBlob =
            response instanceof HttpResponse ? response.body :
            (<any>response).error instanceof Blob ? (<any>response).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }}
        if (status === 200) {
            return blobToText(responseBlob).pipe(_observableMergeMap(_responseText => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = PublishMasterResult.fromJS(resultData200);
            return _observableOf(result200);
            }));
        } else if (status === 400) {
            return blobToText(responseBlob).pipe(_observableMergeMap(_responseText => {
            let result400: any = null;
            let resultData400 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result400 = BadAPIResponse.fromJS(resultData400);
            return throwException("BadAPIResponse", status, _responseText, _headers, result400);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap(_responseText => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf<PublishMasterResult>(<any>null);
    }

    /**
     * @return UnpublishMasterResault
     */
    unpublishMaster(id: string): Observable<UnpublishMasterResault> {
        let url_ = this.baseUrl + "/masters-list/unpublish-master/{id}";
        if (id === undefined || id === null)
            throw new Error("The parameter 'id' must be defined.");
        url_ = url_.replace("{id}", encodeURIComponent("" + id));
        url_ = url_.replace(/[?&]$/, "");

        let options_ : any = {
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
                "Accept": "text/plain"
            })
        };

        return this.http.request("post", url_, options_).pipe(_observableMergeMap((response_ : any) => {
            return this.processUnpublishMaster(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processUnpublishMaster(<any>response_);
                } catch (e) {
                    return <Observable<UnpublishMasterResault>><any>_observableThrow(e);
                }
            } else
                return <Observable<UnpublishMasterResault>><any>_observableThrow(response_);
        }));
    }

    protected processUnpublishMaster(response: HttpResponseBase): Observable<UnpublishMasterResault> {
        const status = response.status;
        const responseBlob =
            response instanceof HttpResponse ? response.body :
            (<any>response).error instanceof Blob ? (<any>response).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }}
        if (status === 200) {
            return blobToText(responseBlob).pipe(_observableMergeMap(_responseText => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = UnpublishMasterResault.fromJS(resultData200);
            return _observableOf(result200);
            }));
        } else if (status === 400) {
            return blobToText(responseBlob).pipe(_observableMergeMap(_responseText => {
            let result400: any = null;
            let resultData400 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result400 = BadAPIResponse.fromJS(resultData400);
            return throwException("BadAPIResponse", status, _responseText, _headers, result400);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap(_responseText => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf<UnpublishMasterResault>(<any>null);
    }

    /**
     * @param body (optional) 
     * @return Success
     */
    updateMaster(id: string, body: UpdateMasterReq | undefined): Observable<void> {
        let url_ = this.baseUrl + "/masters-list/update-master/{id}";
        if (id === undefined || id === null)
            throw new Error("The parameter 'id' must be defined.");
        url_ = url_.replace("{id}", encodeURIComponent("" + id));
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_ : any = {
            body: content_,
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
                "Content-Type": "application/json",
            })
        };

        return this.http.request("post", url_, options_).pipe(_observableMergeMap((response_ : any) => {
            return this.processUpdateMaster(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processUpdateMaster(<any>response_);
                } catch (e) {
                    return <Observable<void>><any>_observableThrow(e);
                }
            } else
                return <Observable<void>><any>_observableThrow(response_);
        }));
    }

    protected processUpdateMaster(response: HttpResponseBase): Observable<void> {
        const status = response.status;
        const responseBlob =
            response instanceof HttpResponse ? response.body :
            (<any>response).error instanceof Blob ? (<any>response).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }}
        if (status === 200) {
            return blobToText(responseBlob).pipe(_observableMergeMap(_responseText => {
            return _observableOf<void>(<any>null);
            }));
        } else if (status === 400) {
            return blobToText(responseBlob).pipe(_observableMergeMap(_responseText => {
            let result400: any = null;
            let resultData400 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result400 = BadAPIResponse.fromJS(resultData400);
            return throwException("BadAPIResponse", status, _responseText, _headers, result400);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap(_responseText => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf<void>(<any>null);
    }

    /**
     * @param file (optional) 
     * @return Success
     */
    uploadAvatar(id: string, file: FileParameter | null | undefined): Observable<void> {
        let url_ = this.baseUrl + "/masters-list/upload-avatar/{id}";
        if (id === undefined || id === null)
            throw new Error("The parameter 'id' must be defined.");
        url_ = url_.replace("{id}", encodeURIComponent("" + id));
        url_ = url_.replace(/[?&]$/, "");

        const content_ = new FormData();
        if (file !== null && file !== undefined)
            content_.append("file", file.data, file.fileName ? file.fileName : "file");

        let options_ : any = {
            body: content_,
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
            })
        };

        return this.http.request("post", url_, options_).pipe(_observableMergeMap((response_ : any) => {
            return this.processUploadAvatar(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processUploadAvatar(<any>response_);
                } catch (e) {
                    return <Observable<void>><any>_observableThrow(e);
                }
            } else
                return <Observable<void>><any>_observableThrow(response_);
        }));
    }

    protected processUploadAvatar(response: HttpResponseBase): Observable<void> {
        const status = response.status;
        const responseBlob =
            response instanceof HttpResponse ? response.body :
            (<any>response).error instanceof Blob ? (<any>response).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }}
        if (status === 200) {
            return blobToText(responseBlob).pipe(_observableMergeMap(_responseText => {
            return _observableOf<void>(<any>null);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap(_responseText => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf<void>(<any>null);
    }
}

export class ServiceTypeRes implements IServiceTypeRes {
    name?: string | undefined;
    serviceTypeSubGroupId?: string;

    constructor(data?: IServiceTypeRes) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.name = _data["name"];
            this.serviceTypeSubGroupId = _data["serviceTypeSubGroupId"];
        }
    }

    static fromJS(data: any): ServiceTypeRes {
        data = typeof data === 'object' ? data : {};
        let result = new ServiceTypeRes();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["name"] = this.name;
        data["serviceTypeSubGroupId"] = this.serviceTypeSubGroupId;
        return data; 
    }
}

export interface IServiceTypeRes {
    name?: string | undefined;
    serviceTypeSubGroupId?: string;
}

export class PriceListItemRes implements IPriceListItemRes {
    id?: string;
    name?: string | undefined;
    serviceType?: ServiceTypeRes;
    priceMin?: number;
    priceMax?: number;
    durationInMinutesMax?: number;

    constructor(data?: IPriceListItemRes) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.id = _data["id"];
            this.name = _data["name"];
            this.serviceType = _data["serviceType"] ? ServiceTypeRes.fromJS(_data["serviceType"]) : <any>undefined;
            this.priceMin = _data["priceMin"];
            this.priceMax = _data["priceMax"];
            this.durationInMinutesMax = _data["durationInMinutesMax"];
        }
    }

    static fromJS(data: any): PriceListItemRes {
        data = typeof data === 'object' ? data : {};
        let result = new PriceListItemRes();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["id"] = this.id;
        data["name"] = this.name;
        data["serviceType"] = this.serviceType ? this.serviceType.toJSON() : <any>undefined;
        data["priceMin"] = this.priceMin;
        data["priceMax"] = this.priceMax;
        data["durationInMinutesMax"] = this.durationInMinutesMax;
        return data; 
    }
}

export interface IPriceListItemRes {
    id?: string;
    name?: string | undefined;
    serviceType?: ServiceTypeRes;
    priceMin?: number;
    priceMax?: number;
    durationInMinutesMax?: number;
}

export enum DayOfWeek {
    _0 = 0,
    _1 = 1,
    _2 = 2,
    _3 = 3,
    _4 = 4,
    _5 = 5,
    _6 = 6,
}

export class Window implements IWindow {
    startTime?: Date;
    endTime?: Date;

    constructor(data?: IWindow) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.startTime = _data["startTime"] ? new Date(_data["startTime"].toString()) : <any>undefined;
            this.endTime = _data["endTime"] ? new Date(_data["endTime"].toString()) : <any>undefined;
        }
    }

    static fromJS(data: any): Window {
        data = typeof data === 'object' ? data : {};
        let result = new Window();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["startTime"] = this.startTime ? this.startTime.toISOString() : <any>undefined;
        data["endTime"] = this.endTime ? this.endTime.toISOString() : <any>undefined;
        return data; 
    }
}

export interface IWindow {
    startTime?: Date;
    endTime?: Date;
}

export class ScheduleDayRes implements IScheduleDayRes {
    dayOfWeek?: DayOfWeek;
    startTime?: Date;
    endTime?: Date;
    windows?: Window[] | undefined;

    constructor(data?: IScheduleDayRes) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.dayOfWeek = _data["dayOfWeek"];
            this.startTime = _data["startTime"] ? new Date(_data["startTime"].toString()) : <any>undefined;
            this.endTime = _data["endTime"] ? new Date(_data["endTime"].toString()) : <any>undefined;
            if (Array.isArray(_data["windows"])) {
                this.windows = [] as any;
                for (let item of _data["windows"])
                    this.windows!.push(Window.fromJS(item));
            }
        }
    }

    static fromJS(data: any): ScheduleDayRes {
        data = typeof data === 'object' ? data : {};
        let result = new ScheduleDayRes();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["dayOfWeek"] = this.dayOfWeek;
        data["startTime"] = this.startTime ? this.startTime.toISOString() : <any>undefined;
        data["endTime"] = this.endTime ? this.endTime.toISOString() : <any>undefined;
        if (Array.isArray(this.windows)) {
            data["windows"] = [];
            for (let item of this.windows)
                data["windows"].push(item.toJSON());
        }
        return data; 
    }
}

export interface IScheduleDayRes {
    dayOfWeek?: DayOfWeek;
    startTime?: Date;
    endTime?: Date;
    windows?: Window[] | undefined;
}

export class MasterRes implements IMasterRes {
    id?: string;
    name?: string | undefined;
    cityId?: string | undefined;
    avatarUrl?: string | undefined;
    thumbnailUrl?: string | undefined;
    about?: string | undefined;
    address?: string | undefined;
    phone?: string | undefined;
    instagramProfile?: string | undefined;
    vkProfile?: string | undefined;
    viber?: string | undefined;
    skype?: string | undefined;
    speciality?: string | undefined;
    priceList?: PriceListItemRes[] | undefined;
    schedule?: ScheduleDayRes[] | undefined;
    averageRating?: number | undefined;

    constructor(data?: IMasterRes) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.id = _data["id"];
            this.name = _data["name"];
            this.cityId = _data["cityId"];
            this.avatarUrl = _data["avatarUrl"];
            this.thumbnailUrl = _data["thumbnailUrl"];
            this.about = _data["about"];
            this.address = _data["address"];
            this.phone = _data["phone"];
            this.instagramProfile = _data["instagramProfile"];
            this.vkProfile = _data["vkProfile"];
            this.viber = _data["viber"];
            this.skype = _data["skype"];
            this.speciality = _data["speciality"];
            if (Array.isArray(_data["priceList"])) {
                this.priceList = [] as any;
                for (let item of _data["priceList"])
                    this.priceList!.push(PriceListItemRes.fromJS(item));
            }
            if (Array.isArray(_data["schedule"])) {
                this.schedule = [] as any;
                for (let item of _data["schedule"])
                    this.schedule!.push(ScheduleDayRes.fromJS(item));
            }
            this.averageRating = _data["averageRating"];
        }
    }

    static fromJS(data: any): MasterRes {
        data = typeof data === 'object' ? data : {};
        let result = new MasterRes();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["id"] = this.id;
        data["name"] = this.name;
        data["cityId"] = this.cityId;
        data["avatarUrl"] = this.avatarUrl;
        data["thumbnailUrl"] = this.thumbnailUrl;
        data["about"] = this.about;
        data["address"] = this.address;
        data["phone"] = this.phone;
        data["instagramProfile"] = this.instagramProfile;
        data["vkProfile"] = this.vkProfile;
        data["viber"] = this.viber;
        data["skype"] = this.skype;
        data["speciality"] = this.speciality;
        if (Array.isArray(this.priceList)) {
            data["priceList"] = [];
            for (let item of this.priceList)
                data["priceList"].push(item.toJSON());
        }
        if (Array.isArray(this.schedule)) {
            data["schedule"] = [];
            for (let item of this.schedule)
                data["schedule"].push(item.toJSON());
        }
        data["averageRating"] = this.averageRating;
        return data; 
    }
}

export interface IMasterRes {
    id?: string;
    name?: string | undefined;
    cityId?: string | undefined;
    avatarUrl?: string | undefined;
    thumbnailUrl?: string | undefined;
    about?: string | undefined;
    address?: string | undefined;
    phone?: string | undefined;
    instagramProfile?: string | undefined;
    vkProfile?: string | undefined;
    viber?: string | undefined;
    skype?: string | undefined;
    speciality?: string | undefined;
    priceList?: PriceListItemRes[] | undefined;
    schedule?: ScheduleDayRes[] | undefined;
    averageRating?: number | undefined;
}

export class BadAPIResponse implements IBadAPIResponse {
    /** Error code */
    code?: string | undefined;
    /** Error messages */
    messages?: string[] | undefined;

    constructor(data?: IBadAPIResponse) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.code = _data["code"];
            if (Array.isArray(_data["messages"])) {
                this.messages = [] as any;
                for (let item of _data["messages"])
                    this.messages!.push(item);
            }
        }
    }

    static fromJS(data: any): BadAPIResponse {
        data = typeof data === 'object' ? data : {};
        let result = new BadAPIResponse();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["code"] = this.code;
        if (Array.isArray(this.messages)) {
            data["messages"] = [];
            for (let item of this.messages)
                data["messages"].push(item);
        }
        return data; 
    }
}

export interface IBadAPIResponse {
    /** Error code */
    code?: string | undefined;
    /** Error messages */
    messages?: string[] | undefined;
}

export class PublishMasterMessage implements IPublishMasterMessage {
    text?: string | undefined;

    constructor(data?: IPublishMasterMessage) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.text = _data["text"];
        }
    }

    static fromJS(data: any): PublishMasterMessage {
        data = typeof data === 'object' ? data : {};
        let result = new PublishMasterMessage();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["text"] = this.text;
        return data; 
    }
}

export interface IPublishMasterMessage {
    text?: string | undefined;
}

export class PublishMasterResult implements IPublishMasterResult {
    result?: boolean;
    messages?: PublishMasterMessage[] | undefined;

    constructor(data?: IPublishMasterResult) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.result = _data["result"];
            if (Array.isArray(_data["messages"])) {
                this.messages = [] as any;
                for (let item of _data["messages"])
                    this.messages!.push(PublishMasterMessage.fromJS(item));
            }
        }
    }

    static fromJS(data: any): PublishMasterResult {
        data = typeof data === 'object' ? data : {};
        let result = new PublishMasterResult();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["result"] = this.result;
        if (Array.isArray(this.messages)) {
            data["messages"] = [];
            for (let item of this.messages)
                data["messages"].push(item.toJSON());
        }
        return data; 
    }
}

export interface IPublishMasterResult {
    result?: boolean;
    messages?: PublishMasterMessage[] | undefined;
}

export class UnpublishMasterMessage implements IUnpublishMasterMessage {
    text?: string | undefined;

    constructor(data?: IUnpublishMasterMessage) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.text = _data["text"];
        }
    }

    static fromJS(data: any): UnpublishMasterMessage {
        data = typeof data === 'object' ? data : {};
        let result = new UnpublishMasterMessage();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["text"] = this.text;
        return data; 
    }
}

export interface IUnpublishMasterMessage {
    text?: string | undefined;
}

export class UnpublishMasterResault implements IUnpublishMasterResault {
    result?: boolean;
    messages?: UnpublishMasterMessage[] | undefined;

    constructor(data?: IUnpublishMasterResault) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.result = _data["result"];
            if (Array.isArray(_data["messages"])) {
                this.messages = [] as any;
                for (let item of _data["messages"])
                    this.messages!.push(UnpublishMasterMessage.fromJS(item));
            }
        }
    }

    static fromJS(data: any): UnpublishMasterResault {
        data = typeof data === 'object' ? data : {};
        let result = new UnpublishMasterResault();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["result"] = this.result;
        if (Array.isArray(this.messages)) {
            data["messages"] = [];
            for (let item of this.messages)
                data["messages"].push(item.toJSON());
        }
        return data; 
    }
}

export interface IUnpublishMasterResault {
    result?: boolean;
    messages?: UnpublishMasterMessage[] | undefined;
}

export class ServiceTypeReq implements IServiceTypeReq {
    id?: string;
    serviceTypeSubGroupId?: string;

    constructor(data?: IServiceTypeReq) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.id = _data["id"];
            this.serviceTypeSubGroupId = _data["serviceTypeSubGroupId"];
        }
    }

    static fromJS(data: any): ServiceTypeReq {
        data = typeof data === 'object' ? data : {};
        let result = new ServiceTypeReq();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["id"] = this.id;
        data["serviceTypeSubGroupId"] = this.serviceTypeSubGroupId;
        return data; 
    }
}

export interface IServiceTypeReq {
    id?: string;
    serviceTypeSubGroupId?: string;
}

export class PriceListItemReq implements IPriceListItemReq {
    id?: string;
    serviceType?: ServiceTypeReq;
    priceMin?: number;
    priceMax?: number;
    durationInMinutesMax?: number;

    constructor(data?: IPriceListItemReq) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.id = _data["id"];
            this.serviceType = _data["serviceType"] ? ServiceTypeReq.fromJS(_data["serviceType"]) : <any>undefined;
            this.priceMin = _data["priceMin"];
            this.priceMax = _data["priceMax"];
            this.durationInMinutesMax = _data["durationInMinutesMax"];
        }
    }

    static fromJS(data: any): PriceListItemReq {
        data = typeof data === 'object' ? data : {};
        let result = new PriceListItemReq();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["id"] = this.id;
        data["serviceType"] = this.serviceType ? this.serviceType.toJSON() : <any>undefined;
        data["priceMin"] = this.priceMin;
        data["priceMax"] = this.priceMax;
        data["durationInMinutesMax"] = this.durationInMinutesMax;
        return data; 
    }
}

export interface IPriceListItemReq {
    id?: string;
    serviceType?: ServiceTypeReq;
    priceMin?: number;
    priceMax?: number;
    durationInMinutesMax?: number;
}

export class UpdateMasterReq implements IUpdateMasterReq {
    name?: string | undefined;
    about?: string | undefined;
    address?: string | undefined;
    phone?: string | undefined;
    instagramProfile?: string | undefined;
    vkProfile?: string | undefined;
    viber?: string | undefined;
    skype?: string | undefined;
    specialityId?: string | undefined;
    priceListItems?: PriceListItemReq[] | undefined;

    constructor(data?: IUpdateMasterReq) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.name = _data["name"];
            this.about = _data["about"];
            this.address = _data["address"];
            this.phone = _data["phone"];
            this.instagramProfile = _data["instagramProfile"];
            this.vkProfile = _data["vkProfile"];
            this.viber = _data["viber"];
            this.skype = _data["skype"];
            this.specialityId = _data["specialityId"];
            if (Array.isArray(_data["priceListItems"])) {
                this.priceListItems = [] as any;
                for (let item of _data["priceListItems"])
                    this.priceListItems!.push(PriceListItemReq.fromJS(item));
            }
        }
    }

    static fromJS(data: any): UpdateMasterReq {
        data = typeof data === 'object' ? data : {};
        let result = new UpdateMasterReq();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["name"] = this.name;
        data["about"] = this.about;
        data["address"] = this.address;
        data["phone"] = this.phone;
        data["instagramProfile"] = this.instagramProfile;
        data["vkProfile"] = this.vkProfile;
        data["viber"] = this.viber;
        data["skype"] = this.skype;
        data["specialityId"] = this.specialityId;
        if (Array.isArray(this.priceListItems)) {
            data["priceListItems"] = [];
            for (let item of this.priceListItems)
                data["priceListItems"].push(item.toJSON());
        }
        return data; 
    }
}

export interface IUpdateMasterReq {
    name?: string | undefined;
    about?: string | undefined;
    address?: string | undefined;
    phone?: string | undefined;
    instagramProfile?: string | undefined;
    vkProfile?: string | undefined;
    viber?: string | undefined;
    skype?: string | undefined;
    specialityId?: string | undefined;
    priceListItems?: PriceListItemReq[] | undefined;
}

export interface FileParameter {
    data: any;
    fileName: string;
}

export class ApiException extends Error {
    message: string;
    status: number;
    response: string;
    headers: { [key: string]: any; };
    result: any;

    constructor(message: string, status: number, response: string, headers: { [key: string]: any; }, result: any) {
        super();

        this.message = message;
        this.status = status;
        this.response = response;
        this.headers = headers;
        this.result = result;
    }

    protected isApiException = true;

    static isApiException(obj: any): obj is ApiException {
        return obj.isApiException === true;
    }
}

function throwException(message: string, status: number, response: string, headers: { [key: string]: any; }, result?: any): Observable<any> {
    return _observableThrow(new ApiException(message, status, response, headers, result));
}

function blobToText(blob: any): Observable<string> {
    return new Observable<string>((observer: any) => {
        if (!blob) {
            observer.next("");
            observer.complete();
        } else {
            let reader = new FileReader();
            reader.onload = event => {
                observer.next((<any>event.target).result);
                observer.complete();
            };
            reader.readAsText(blob);
        }
    });
}