POST http://localhost:5210/api/masters-list/update-master/38f21320-c9ed-46bd-ae6d-af9df01d080b
Content-Type: application/json

{
"Name": "John KEK",
"AvatarUrl": "https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.reddit.com%2Fr%2Fforsen%2Fcomments%2F4eizkt%2Fdungeon_master_if_you_upvote_this_this_will%2F&psig=AOvVaw0HjC5DZPYb5oKMQWmM44MF&ust=1604004184682000&source=images&cd=vfe&ved=0CAIQjRxqFwoTCIDsjLmT2OwCFQAAAAAdAAAAABAD",
"About": null,
"Address": "Чайковского-11",
"Phone": "",
"InstagramProfile": null,
"VkProfile": null,
"Viber": null,
"Skype": null,
"SpecialityId": null,
"PriceListItems": []
}
