POST http://localhost:5222/masters-list/upload-avatar/dc46d935-b34f-4c89-8aec-828a2119003c
Content-Type: multipart/form-data; boundary=WebAppBoundary
Connection: keep-alive

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="file.jpg"

< ./UploadAvatarImage.jpg
--WebAppBoundary--